### ISSUE TITLE
Cython Compiler Error During Installation

### ISSUE THREAD

**Issue by artunboz** [rsverhagen94/TUD-Collaborative-AI-2023#1]
I am having trouble installing the TUD-Collaborative-AI-2023 repository. Specifically, the command `pip install -r requirements.txt` results in a compilation error, which you can find down below.

I have tried using python versions 3.8.16 and 3.9.16, but the issue persisted. My pip version is 22.0.4. I am on macOS 13.1.

**Error message:**
```
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef load_traceback
      cdef Waiter
      cdef wait
      cdef iwait
      cdef reraise
      cpdef GEVENT_CONFIG
            ^
      ------------------------------------------------------------
      src/gevent/_gevent_cgreenlet.pxd:182:6: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      Compiling src/gevent/greenlet.py because it changed.
      [1/1] Cythonizing src/gevent/greenlet.py
      Traceback (most recent call last):
        File "/Users/artun/venvs/cai/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/artun/venvs/cai/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/artun/venvs/cai/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/v9/wmcmdrdd7bxcd_p5hq_4pyn40000gn/T/pip-build-env-tshzzuvo/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/v9/wmcmdrdd7bxcd_p5hq_4pyn40000gn/T/pip-build-env-tshzzuvo/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/v9/wmcmdrdd7bxcd_p5hq_4pyn40000gn/T/pip-build-env-tshzzuvo/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/v9/wmcmdrdd7bxcd_p5hq_4pyn40000gn/T/pip-build-env-tshzzuvo/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 294, in <module>
        File "/private/var/folders/v9/wmcmdrdd7bxcd_p5hq_4pyn40000gn/T/pip-install-pcqxbmp5/gevent_b6054b236300487b91e209ea64820dfb/_setuputils.py", line 237, in cythonize1
          new_ext = cythonize(
        File "/private/var/folders/v9/wmcmdrdd7bxcd_p5hq_4pyn40000gn/T/pip-build-env-tshzzuvo/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1129, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/v9/wmcmdrdd7bxcd_p5hq_4pyn40000gn/T/pip-build-env-tshzzuvo/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1296, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/gevent/greenlet.py
      [end of output]
```

**My attempts at solving it:**
I have found this relevant issue in the repo of gevent: https://github.com/gevent/gevent/issues/1899

There, the official suggested fix is to simply use a newer version of gevent. Furthermore, I have tried removing either gevent or greenlet from the requirements.txt file and installing the requirements. Neither worked. **However,** removing both at the same time did work. Now, when I run `pip freeze`, the output is the following:

```
bidict==0.21.2
certifi==2022.12.7
chardet==4.0.0
charset-normalizer==3.0.1
click==8.1.3
colour==0.1.5
docutils==0.16
Flask==2.1.3
Flask-Cors==3.0.10
Flask-SocketIO==5.3.2
gevent==22.10.2
greenlet==2.0.2
idna==3.4
importlib-metadata==6.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jsonpickle==1.5.1
MarkupSafe==2.1.2
matrx==2.2.0
numpy==1.20.0
Pygments==2.14.0
python-engineio==4.3.4
python-socketio==5.7.2
requests==2.28.2
six==1.16.0
urllib3==1.26.14
Werkzeug==2.0.0
zipp==3.14.0
zope.event==4.6
zope.interface==5.5.2
```

Note that gevent and greenlet are both installed (as transitive dependencies), but their versions are higher. Thus, my instinct is that the compilation error is due to versioning indeed. Finally, I have tried to play the game a bit to see if the game is properly working. It seems like it is, except some formatting issues such as the dialogue box not fitting the screen unless I am running it on fullscreen.

**Comment by rsverhagen94** [comment]
Hi @artunboz. Thank you for creating the extensive issue together with a solution already! I'll make sure to double check and update the requirements file. 

Regarding the dialogue box not fitting the screen: if I remember well you can zoom out on the page, this should only change the size of the chat and not the world.

**Comment by artunboz** [comment]
> Hi @artunboz. Thank you for creating the extensive issue together with a solution already! I'll make sure to double check and update the requirements file.
> 
> Regarding the dialogue box not fitting the screen: if I remember well you can zoom out on the page, this should only change the size of the chat and not the world.

Sounds good!

**Comment by paulmis** [comment]
@rsverhagen94 also running into this!

**Comment by rsverhagen94** [comment]
@paulmis did the solution described by @artunboz solve your issue?
